local Engine = {}

local VALID_CAPITALIZATION = {
    none = true,
    force_uppercase = true,
    force_lowercase = true,
}

local UNICODE_PUNCTUATION = {
    ["«"] = true,
    ["»"] = true,
    ["—"] = true,
    ["–"] = true,
    ["…"] = true,
    ["’"] = true,
    ["‘"] = true,
    ["“"] = true,
    ["”"] = true,
}

local UNICODE_WHITESPACE = {
    ["\u{00a0}"] = true,
    ["\u{1680}"] = true,
    ["\u{2000}"] = true,
    ["\u{2001}"] = true,
    ["\u{2002}"] = true,
    ["\u{2003}"] = true,
    ["\u{2004}"] = true,
    ["\u{2005}"] = true,
    ["\u{2006}"] = true,
    ["\u{2007}"] = true,
    ["\u{2008}"] = true,
    ["\u{2009}"] = true,
    ["\u{200a}"] = true,
    ["\u{2028}"] = true,
    ["\u{2029}"] = true,
    ["\u{202f}"] = true,
    ["\u{205f}"] = true,
    ["\u{3000}"] = true,
}

-- Structural delimiters generated by replacements remain wrapped in
-- noncharacters until every rule has run. Later punctuation-trimming rules
-- therefore cannot mistake ], ), or ” for punctuation added by Whisper.
local PROTECTION_START = utf8.char(0xfdd0)
local PROTECTION_END = utf8.char(0xfdd1)
local PROTECTED_DELIMITERS = {
    "(", ")", "[", "]", "{", "}", "“", "”", "‘", "’", "«", "»",
}

local function isProtectionMarker(char)
    return char == PROTECTION_START or char == PROTECTION_END
end

local function replacePlain(text, needle, replacement)
    local result = {}
    local position = 1

    while true do
        local startByte, endByte = text:find(needle, position, true)
        if not startByte then
            result[#result + 1] = text:sub(position)
            break
        end

        result[#result + 1] = text:sub(position, startByte - 1)
        result[#result + 1] = replacement
        position = endByte + 1
    end

    return table.concat(result)
end

local function protectReplacement(text)
    local result = text
    for _, delimiter in ipairs(PROTECTED_DELIMITERS) do
        result = replacePlain(
            result,
            delimiter,
            PROTECTION_START .. delimiter .. PROTECTION_END
        )
    end
    return result
end

local function removeProtectionMarkers(text)
    return (text:gsub(PROTECTION_START, ""):gsub(PROTECTION_END, ""))
end

local function characterRecords(text)
    local records = {}
    local valid = pcall(function()
        for byteIndex, codepoint in utf8.codes(text) do
            local char = utf8.char(codepoint)
            records[#records + 1] = {
                char = char,
                codepoint = codepoint,
                startByte = byteIndex,
                endByte = byteIndex + #char - 1,
            }
        end
    end)

    if valid then
        return records
    end

    -- Clipboard strings should be UTF-8, but preserve invalid input rather
    -- than failing a dictation if another application supplied raw bytes.
    records = {}
    for index = 1, #text do
        records[#records + 1] = {
            char = text:sub(index, index),
            codepoint = text:byte(index),
            startByte = index,
            endByte = index,
        }
    end
    return records
end

local lowerByChar = {}
local upperByChar = {}
local accentBase = {}

for byte = string.byte("A"), string.byte("Z") do
    local upper = string.char(byte)
    local lower = string.char(byte + 32)
    lowerByChar[upper] = lower
    lowerByChar[lower] = lower
    upperByChar[upper] = upper
    upperByChar[lower] = upper
end

local function registerAccentGroup(upperBase, lowerBase, uppers, lowers)
    local upperChars = characterRecords(uppers)
    local lowerChars = characterRecords(lowers)

    for index, upperRecord in ipairs(upperChars) do
        local lowerRecord = lowerChars[index]
        if lowerRecord then
            local upper = upperRecord.char
            local lower = lowerRecord.char
            lowerByChar[upper] = lower
            lowerByChar[lower] = lower
            upperByChar[upper] = upper
            upperByChar[lower] = upper
            accentBase[upper] = upperBase
            accentBase[lower] = lowerBase
        end
    end
end

registerAccentGroup("A", "a", "ÀÁÂÃÄÅ", "àáâãäå")
registerAccentGroup("E", "e", "ÈÉÊË", "èéêë")
registerAccentGroup("I", "i", "ÌÍÎÏ", "ìíîï")
registerAccentGroup("O", "o", "ÒÓÔÕÖ", "òóôõö")
registerAccentGroup("U", "u", "ÙÚÛÜ", "ùúûü")
registerAccentGroup("Y", "y", "ÝŸ", "ýÿ")
registerAccentGroup("C", "c", "Ç", "ç")
registerAccentGroup("N", "n", "Ñ", "ñ")

local function isCombiningMark(codepoint)
    return (codepoint >= 0x0300 and codepoint <= 0x036f)
        or (codepoint >= 0x1ab0 and codepoint <= 0x1aff)
        or (codepoint >= 0x1dc0 and codepoint <= 0x1dff)
        or (codepoint >= 0x20d0 and codepoint <= 0x20ff)
        or (codepoint >= 0xfe20 and codepoint <= 0xfe2f)
end

local function isWhitespace(char)
    return char:match("^%s$") ~= nil or UNICODE_WHITESPACE[char] == true
end

local function isHorizontalSpace(char)
    return char == " " or char == "\t"
end

local function isPunctuation(char)
    return char:match("^%p$") ~= nil or UNICODE_PUNCTUATION[char] == true
end

local function isWordChar(char, codepoint)
    if isProtectionMarker(char) then
        return false
    end

    if char:match("^[%w_]$") then
        return true
    end

    return codepoint >= 0x80
        and not isWhitespace(char)
        and not isPunctuation(char)
        and not isCombiningMark(codepoint)
end

local function lowerChar(char)
    return lowerByChar[char] or string.lower(char)
end

local function upperChar(char)
    return upperByChar[char] or string.upper(char)
end

local function foldChar(record, matchCase, accentInsensitive)
    if accentInsensitive and isCombiningMark(record.codepoint) then
        return nil
    end

    local value = record.char
    if accentInsensitive then
        value = accentBase[value] or value
    end
    if not matchCase then
        value = lowerChar(value)
    end
    return value
end

local function foldedUnits(text, matchCase, accentInsensitive)
    local units = {}

    for _, record in ipairs(characterRecords(text)) do
        local token = foldChar(record, matchCase, accentInsensitive)
        if token == nil and #units > 0 then
            units[#units].endByte = record.endByte
        elseif token ~= nil then
            units[#units + 1] = {
                token = token,
                char = record.char,
                codepoint = record.codepoint,
                startByte = record.startByte,
                endByte = record.endByte,
            }
        end
    end

    return units
end

local function tableSliceToString(records, first, last)
    if first > last then
        return ""
    end

    local result = {}
    for index = first, last do
        result[#result + 1] = records[index].char
    end
    return table.concat(result)
end

local function trimOuterWhitespace(text)
    local chars = characterRecords(text)
    local first = 1
    local last = #chars

    while first <= last and isWhitespace(chars[first].char) do
        first = first + 1
    end
    while last >= first and isWhitespace(chars[last].char) do
        last = last - 1
    end

    return tableSliceToString(chars, first, last)
end

local function trimPunctuationBefore(text)
    local chars = characterRecords(text)
    local index = #chars

    while index > 0 and isHorizontalSpace(chars[index].char) do
        index = index - 1
    end

    local punctuationEnd = index
    while index > 0 and isPunctuation(chars[index].char) do
        index = index - 1
    end

    if index == punctuationEnd then
        return text
    end

    return tableSliceToString(chars, 1, index)
        .. tableSliceToString(chars, punctuationEnd + 1, #chars)
end

local function trimHorizontalBefore(text)
    return (text:gsub("[ \t]+$", ""))
end

local function trimPunctuationAfter(text, discardLeadingSpaces)
    local chars = characterRecords(text)
    local index = 1

    while index <= #chars and isHorizontalSpace(chars[index].char) do
        index = index + 1
    end

    local punctuationStart = index
    while index <= #chars and isPunctuation(chars[index].char) do
        index = index + 1
    end

    if index == punctuationStart then
        return text
    end

    local preservedSpaces = ""
    if not discardLeadingSpaces then
        preservedSpaces = tableSliceToString(chars, 1, punctuationStart - 1)
    end

    return preservedSpaces .. tableSliceToString(chars, index, #chars)
end

local function trimHorizontalAfter(text)
    return (text:gsub("^[ \t]+", ""))
end

local function capitalizeNextWord(text, capitalizationRule)
    if capitalizationRule == "none" then
        return text
    end

    local chars = characterRecords(text)
    for _, record in ipairs(chars) do
        if not isProtectionMarker(record.char)
            and isWordChar(record.char, record.codepoint)
        then
            local replacement = record.char
            if capitalizationRule == "force_uppercase" then
                replacement = upperChar(record.char)
            elseif capitalizationRule == "force_lowercase" then
                replacement = lowerChar(record.char)
            end

            return text:sub(1, record.startByte - 1)
                .. replacement
                .. text:sub(record.endByte + 1)
        end
    end

    return text
end

local function matchesWholeWord(units, first, last)
    local firstUnit = units[first]
    local lastUnit = units[last]
    local previous = units[first - 1]
    local following = units[last + 1]

    if previous
        and isWordChar(previous.char, previous.codepoint)
        and isWordChar(firstUnit.char, firstUnit.codepoint)
    then
        return false
    end

    if following
        and isWordChar(following.char, following.codepoint)
        and isWordChar(lastUnit.char, lastUnit.codepoint)
    then
        return false
    end

    return true
end

local function findLiteralMatches(text, rule, search)
    local haystack = foldedUnits(
        text,
        rule.match_case,
        rule.accent_insensitive
    )
    local needle = foldedUnits(
        search,
        rule.match_case,
        rule.accent_insensitive
    )
    local matches = {}

    if #needle == 0 or #needle > #haystack then
        return matches
    end

    local index = 1
    while index <= #haystack - #needle + 1 do
        local matched = true
        for offset = 1, #needle do
            if haystack[index + offset - 1].token ~= needle[offset].token then
                matched = false
                break
            end
        end

        local last = index + #needle - 1
        if matched and (not rule.match_whole_word or matchesWholeWord(haystack, index, last)) then
            matches[#matches + 1] = {
                startByte = haystack[index].startByte,
                endByte = haystack[last].endByte,
            }
            index = last + 1
        else
            index = index + 1
        end
    end

    return matches
end

local function byteBoundaryCharacters(text, startByte, endByte)
    local previous = nil
    local following = nil

    for _, record in ipairs(characterRecords(text)) do
        if record.endByte < startByte then
            previous = record
        elseif record.startByte > endByte then
            following = record
            break
        end
    end

    return previous, following
end

local function findPatternMatches(text, rule, search)
    local matches = {}
    local position = 1

    while position <= #text do
        local ok, startByte, endByte = pcall(string.find, text, search, position)
        if not ok or not startByte then
            break
        end
        if endByte < startByte then
            break
        end

        local wholeWord = true
        if rule.match_whole_word then
            local previous, following = byteBoundaryCharacters(text, startByte, endByte)
            local matchedText = text:sub(startByte, endByte)
            local matchedChars = characterRecords(matchedText)
            local first = matchedChars[1]
            local last = matchedChars[#matchedChars]

            if first and previous
                and isWordChar(first.char, first.codepoint)
                and isWordChar(previous.char, previous.codepoint)
            then
                wholeWord = false
            end
            if last and following
                and isWordChar(last.char, last.codepoint)
                and isWordChar(following.char, following.codepoint)
            then
                wholeWord = false
            end
        end

        if wholeWord then
            matches[#matches + 1] = {
                startByte = startByte,
                endByte = endByte,
            }
        end

        position = endByte + 1
    end

    return matches
end

local function findRuleMatches(text, rule)
    local candidates = {}

    for searchIndex, search in ipairs(rule.searches) do
        local aliasMatches
        if rule.is_regex then
            aliasMatches = findPatternMatches(text, rule, search)
        else
            aliasMatches = findLiteralMatches(text, rule, search)
        end

        for _, match in ipairs(aliasMatches) do
            match.searchIndex = searchIndex
            candidates[#candidates + 1] = match
        end
    end

    -- Prefer the earliest match, then the longest alias at the same position.
    -- This makes overlapping aliases deterministic and prevents replacing the
    -- same text more than once when aliases overlap or are duplicated.
    table.sort(candidates, function(left, right)
        if left.startByte ~= right.startByte then
            return left.startByte < right.startByte
        end
        if left.endByte ~= right.endByte then
            return left.endByte > right.endByte
        end
        return left.searchIndex < right.searchIndex
    end)

    local matches = {}
    local nextAvailableByte = 1
    for _, candidate in ipairs(candidates) do
        if candidate.startByte >= nextAvailableByte then
            matches[#matches + 1] = candidate
            nextAvailableByte = candidate.endByte + 1
        end
    end

    return matches
end


local function parseMagicTags(replacement)
    local transformations = {}

    local cleaned = replacement:gsub("%[([%a]+)%]", function(tag)
        if tag == "date" then
            return os.date("%Y-%m-%d")
        elseif tag == "time" then
            return os.date("%H:%M")
        elseif tag == "lowercase" or tag == "lowcase" then
            transformations[#transformations + 1] = "lowercase"
            return ""
        elseif tag == "uppercase" then
            transformations[#transformations + 1] = "uppercase"
            return ""
        elseif tag == "capitalize" then
            transformations[#transformations + 1] = "capitalize"
            return ""
        elseif tag == "nospace" then
            transformations[#transformations + 1] = "nospace"
            return ""
        end

        return "[" .. tag .. "]"
    end)

    return (cleaned:gsub("\\n", "\n")), transformations
end

local function mapCharacters(text, mapper)
    local result = {}
    for _, record in ipairs(characterRecords(text)) do
        result[#result + 1] = mapper(record.char)
    end
    return table.concat(result)
end

local function capitalizeWords(text)
    local result = {}
    local capitalizeNext = true

    for _, record in ipairs(characterRecords(text)) do
        local char = record.char
        if isProtectionMarker(char) then
            result[#result + 1] = char
        elseif isWhitespace(char) or isPunctuation(char) then
            capitalizeNext = true
            result[#result + 1] = char
        elseif capitalizeNext then
            result[#result + 1] = upperChar(char)
            capitalizeNext = false
        else
            result[#result + 1] = char
        end
    end

    return table.concat(result)
end

local function applyTransformations(text, transformations)
    local result = text

    for _, transformation in ipairs(transformations) do
        if transformation == "lowercase" then
            result = mapCharacters(result, lowerChar)
        elseif transformation == "uppercase" then
            result = mapCharacters(result, upperChar)
        elseif transformation == "capitalize" then
            result = capitalizeWords(result)
        elseif transformation == "nospace" then
            result = result:gsub(" ", "")
        end
    end

    return result
end

local function patternValidationError(pattern)
    local ok, errorMessage = pcall(string.find, "validation", pattern, 1)
    if not ok then
        return tostring(errorMessage)
    end

    for _, sample in ipairs({"", "x", " "}) do
        local sampleOk, startByte, endByte = pcall(string.find, sample, pattern, 1)
        if sampleOk and startByte and endByte < startByte then
            return "patterns that match empty text are not supported"
        end
    end

    return nil
end

local function normalizeRule(rule, index)
    if type(rule) ~= "table" then
        return nil, "rule " .. index .. " is not an object"
    end

    local searches = {}
    if type(rule.search) == "string" then
        searches[1] = rule.search
    elseif type(rule.search) == "table" then
        for aliasIndex, search in ipairs(rule.search) do
            if type(search) ~= "string" or search == "" then
                return nil, "rule " .. index .. " search alias " .. aliasIndex
                    .. " is not a non-empty string"
            end
            searches[#searches + 1] = search
        end
    else
        return nil, "rule " .. index
            .. " search must be a non-empty string or array of strings"
    end
    if #searches == 0 or searches[1] == "" then
        return nil, "rule " .. index
            .. " search must be a non-empty string or array of strings"
    end
    if type(rule.replace) ~= "string" then
        return nil, "rule " .. index .. " has no replacement string"
    end
    if rule.replace:find("[run]", 1, true) then
        return nil, "rule " .. index .. " uses disabled [run] command execution"
    end

    local capitalization = rule.capitalization_rule or "none"
    if not VALID_CAPITALIZATION[capitalization] then
        return nil, "rule " .. index .. " has an invalid capitalization_rule"
    end

    local normalized = {
        search = rule.search,
        searches = searches,
        replace = rule.replace,
        enabled = rule.enabled ~= false,
        is_regex = rule.is_regex == true,
        match_case = rule.match_case == true,
        accent_insensitive = rule.accent_insensitive ~= false,
        match_whole_word = rule.match_whole_word == true,
        trim_punctuation_before = rule.trim_punctuation_before == true,
        trim_punctuation_after = rule.trim_punctuation_after == true,
        trim_spaces_before = rule.trim_spaces_before == true,
        trim_spaces_after = rule.trim_spaces_after == true,
        capitalization_rule = capitalization,
    }

    if normalized.is_regex then
        for aliasIndex, search in ipairs(normalized.searches) do
            local patternError = patternValidationError(search)
            if patternError then
                return nil, "rule " .. index .. " search alias " .. aliasIndex
                    .. " has an invalid Lua pattern: " .. patternError
            end
        end
    end

    return normalized
end

function Engine.validateConfig(config)
    if type(config) ~= "table" then
        return nil, {"configuration root is not an object or array"}
    end

    local rawRules
    if config.replacements ~= nil then
        rawRules = config.replacements
    elseif config[1] ~= nil or next(config) == nil then
        -- Accept the array exported by the Handy fork directly.
        rawRules = config
    else
        return nil, {"configuration has no replacements array"}
    end

    if type(rawRules) ~= "table" then
        return nil, {"replacements is not an array"}
    end

    local normalized = {
        enabled = config.enabled ~= false,
        trim_input = config.trim_input ~= false,
        replacements = {},
    }
    local errors = {}

    for index, rule in ipairs(rawRules) do
        local validRule, errorMessage = normalizeRule(rule, index)
        if validRule then
            normalized.replacements[#normalized.replacements + 1] = validRule
        else
            errors[#errors + 1] = errorMessage
        end
    end

    return normalized, errors
end

function Engine.processValidated(text, config)
    if type(text) ~= "string" then
        return text, {rulesApplied = 0, matches = 0}
    end

    local result = config.trim_input and trimOuterWhitespace(text) or text
    local transformations = {}
    local stats = {rulesApplied = 0, matches = 0}

    if not config.enabled then
        return result, stats
    end

    for _, rule in ipairs(config.replacements) do
        if rule.enabled then
            local matches = findRuleMatches(result, rule)

            if #matches > 0 then
                local replacement, ruleTransformations = parseMagicTags(rule.replace)
                local protectedReplacement = protectReplacement(replacement)

                -- Work from the end so byte offsets for earlier matches remain
                -- stable while contextual punctuation/space edits are applied.
                for matchIndex = #matches, 1, -1 do
                    local match = matches[matchIndex]
                    local before = result:sub(1, match.startByte - 1)
                    local after = result:sub(match.endByte + 1)

                    if rule.trim_punctuation_before then
                        before = trimPunctuationBefore(before)
                    end
                    if rule.trim_spaces_before then
                        before = trimHorizontalBefore(before)
                    end
                    if rule.trim_punctuation_after then
                        after = trimPunctuationAfter(after, rule.trim_spaces_after)
                    end
                    if rule.trim_spaces_after then
                        after = trimHorizontalAfter(after)
                    end

                    after = capitalizeNextWord(after, rule.capitalization_rule)
                    result = before .. protectedReplacement .. after
                end

                for _, transformation in ipairs(ruleTransformations) do
                    transformations[#transformations + 1] = transformation
                end

                stats.rulesApplied = stats.rulesApplied + 1
                stats.matches = stats.matches + #matches
            end
        end
    end

    result = applyTransformations(result, transformations)
    return removeProtectionMarkers(result), stats
end

function Engine.process(text, config)
    local normalized, errors = Engine.validateConfig(config)
    if not normalized then
        return text, {rulesApplied = 0, matches = 0, errors = errors}
    end

    local result, stats = Engine.processValidated(text, normalized)
    stats.errors = errors
    return result, stats
end

function Engine.runTests()
    local cases = {
        {
            name = "spoken punctuation and duplicate removal",
            input = "Flowers. period Hello comma world period",
            expected = "Flowers. Hello, world.",
            config = {
                trim_input = false,
                replacements = {
                    {search = "period", replace = ".", match_whole_word = true, trim_punctuation_before = true, trim_spaces_before = true},
                    {search = "comma", replace = ",", match_whole_word = true, trim_punctuation_before = true, trim_spaces_before = true},
                },
            },
        },
        {
            name = "paragraph whitespace",
            input = "one new paragraph two",
            expected = "one\n\ntwo",
            config = {replacements = {{search = "new paragraph", replace = "\\n\\n", trim_spaces_before = true, trim_spaces_after = true}}},
        },
        {
            name = "accent-insensitive literal",
            input = "CAFÉ",
            expected = "bistro",
            config = {replacements = {{search = "cafe", replace = "bistro"}}},
        },
        {
            name = "next-word capitalization",
            input = "stop command next",
            expected = "stop. Next",
            config = {replacements = {{search = "command", replace = ".", trim_spaces_before = true, capitalization_rule = "force_uppercase"}}},
        },
        {
            name = "global magic transformation",
            input = "quiet now",
            expected = "SPEAK NOW",
            config = {replacements = {{search = "quiet", replace = "[uppercase]speak"}}},
        },
        {
            name = "Lua pattern",
            input = "item 123",
            expected = "item #",
            config = {replacements = {{search = "%d+", replace = "#", is_regex = true}}},
        },
        {
            name = "literal search aliases",
            input = "one closed paren two close paren three close Perrin",
            expected = "one) two) three)",
            config = {
                replacements = {{
                    search = {"closed paren", "close paren", "close Perrin"},
                    replace = ")",
                    match_whole_word = true,
                    trim_spaces_before = true,
                }},
            },
        },
        {
            name = "longest overlapping search alias wins",
            input = "open parent",
            expected = "(",
            config = {
                replacements = {{
                    search = {"open", "open parent"},
                    replace = "(",
                    match_whole_word = true,
                }},
            },
        },
        {
            name = "Lua pattern search aliases",
            input = "item 123 and code ABC",
            expected = "item # and code #",
            config = {
                replacements = {{
                    search = {"%d+", "%u+"},
                    replace = "#",
                    is_regex = true,
                }},
            },
        },
        {
            name = "later rules preserve delimiter and deduplicate punctuation",
            input = "open bracket items close bracket period new line next",
            expected = "[items].\nNext",
            config = {
                replacements = {
                    {search = "new line", replace = ".\\n", trim_punctuation_before = true, trim_spaces_before = true, trim_punctuation_after = true, trim_spaces_after = true, capitalization_rule = "force_uppercase"},
                    {search = "open bracket", replace = "[", trim_spaces_after = true},
                    {search = "close bracket", replace = "]", trim_spaces_before = true},
                    {search = "period", replace = ".", trim_punctuation_before = true, trim_spaces_before = true, trim_punctuation_after = true, capitalization_rule = "force_uppercase"},
                },
            },
        },
    }

    local failures = {}
    for _, case in ipairs(cases) do
        local actual = Engine.process(case.input, case.config)
        if actual ~= case.expected then
            failures[#failures + 1] = {
                name = case.name,
                expected = case.expected,
                actual = actual,
            }
        end
    end

    local _, unsafeErrors = Engine.validateConfig({
        replacements = {{search = "unsafe", replace = "[run]echo nope"}},
    })
    if #unsafeErrors ~= 1 then
        failures[#failures + 1] = {
            name = "unsafe run tag rejection",
            expected = "one validation error",
            actual = tostring(#unsafeErrors),
        }
    end

    return #failures == 0, failures
end

return Engine
